# Numpy Assignment

In [1]:
import numpy as np

# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [2]:
l = [0, 1, 2, 3, 4, 5]
arr = np.array(l)

In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
print(arr.dtype)

int64


# 2. Given a NumPy array 'arr', check if its data type is float64.
      arr = np.array([1.5, 2.6, 3.7])

In [5]:
arr = np.array([1.5, 2.6, 3.7])

In [6]:
arr.dtype

dtype('float64')

# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [7]:
import numpy as np

arr = np.array([1+3j, 5+7j, 4+9j], dtype = np.complex128)
print(arr)

[1.+3.j 5.+7.j 4.+9.j]


# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [8]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])

a = arr.astype(np.float32)

print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5.]
float32


# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [9]:
import numpy as np

arr = np.array([1.123456789, 2.987654321, 3.456789012], dtype = np.float64)

arr_float32 = arr.astype(np.float32)

print("Original array (float64):", arr)
print("Converted array (float32):", arr_float32)

Original array (float64): [1.12345679 2.98765432 3.45678901]
Converted array (float32): [1.1234568 2.9876542 3.456789 ]


# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [11]:
import numpy as np

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    data_type = arr.dtype
    return shape, size, data_type

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_attributes(arr))

((2, 3), 6, dtype('int64'))


# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [12]:
import numpy as np

def array_dimension(arr):
    return arr.ndim

arr = np.array([[4, 5, 6], [7, 8, 9]])
print(array_dimension(arr)) 

2


# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [13]:
import numpy as np

def item_size_info(array):
    if not isinstance(array, np.ndarray):
        raise TypeError("Input must be a NumPy array")
    
    item_size = array.itemsize
    
    total_size = array.nbytes
    
    return item_size, total_size

if __name__ == "__main__":
    arr = np.array([1, 2, 3, 4, 5])
    item_size, total_size = item_size_info(arr)
    print(f"Item size: {item_size} bytes")
    print(f"Total size: {total_size} bytes")

Item size: 8 bytes
Total size: 40 bytes


# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [14]:
import numpy as np

def array_strides(array):
    return array.strides

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_strides(arr))

(24, 8)


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [15]:
import numpy as np

def shape_stride_relationship(array):

    shape = array.shape
    strides = array.strides
    return shape, strides

arr = np.zeros((3, 4, 2))
arr_shape, arr_strides = shape_stride_relationship(arr)
print("Shape:", arr_shape)
print("Strides:", arr_strides)

Shape: (3, 4, 2)
Strides: (64, 16, 8)


# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [16]:
import numpy as np

def create_zeros_array(n):

    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)

[0. 0. 0. 0. 0.]


# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [18]:
import numpy as np

def create_ones_matrix(rows, cols):

    return np.ones((rows, cols))

rows = 4
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [19]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

start = 0
stop = 10
step = 2
result = generate_range_array(start, stop, step)
print(result)

[0 2 4 6 8]


# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [20]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start = 0
stop = 10
num = 5
result = generate_linear_space(start, stop, num)
print(result)

[ 0.   2.5  5.   7.5 10. ]


# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [21]:
import numpy as np

def create_identity_matrix(n):

    return np.eye(n)

n = 5
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 16. Write a function that takes a Python list and converts it into a NumPy array.

In [22]:
import numpy as np

def list_to_numpy_array(input_list):
    return np.array(input_list)

python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print(numpy_array)

[1 2 3 4 5]


# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [23]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])

view_array = original_array.view()

view_array[0, 0] = 100

print("Original Array:")
print(original_array)
print("\nView Array:")
print(view_array)

Original Array:
[[100   2   3]
 [  4   5   6]]

View Array:
[[100   2   3]
 [  4   5   6]]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [24]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):

    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

concatenated_arr = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:")
print(concatenated_arr)

concatenated_arr = concatenate_arrays(arr1, arr2.T, axis=1)
print("\nConcatenated along axis 1:")
print(concatenated_arr)

Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]]

Concatenated along axis 1:
[[1 2 5]
 [3 4 6]]


# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [25]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7],
                    [8]])

concatenated_array = np.concatenate((array1, array2), axis=1)

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Concatenated array:")
print(concatenated_array)

Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[7]
 [8]]
Concatenated array:
[[1 2 3 7]
 [4 5 6 8]]


# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [26]:
import numpy as np

def stack_arrays_vertically(arrays):

    stacked_array = np.vstack(arrays)
    return stacked_array

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

array3 = np.array([[13, 14, 15],
                   [16, 17, 18]])

arrays_list = [array1, array2, array3]

result = stack_arrays_vertically(arrays_list)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [27]:
import numpy as np

def create_array(start, stop, step):

    return np.arange(start, stop + 1, step, dtype = int)

start = 0
stop = 10
step = 2
result_array = create_array(start, stop, step)
print(result_array)

[ 0  2  4  6  8 10]


# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [28]:
import numpy as np

def generate_array():
    return np.linspace(0, 1, 10)

print(generate_array())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [29]:
import numpy as np

def log_spaced_values(start, end, num):
    return np.logspace(np.log10(start), np.log10(end), num=num)

log_values = log_spaced_values(1, 1000, 5)
print(log_values)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [30]:
import numpy as np
import pandas as pd

data = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(data, columns = ['Column1', 'Column2', 'Column3'])

print(df)

   Column1  Column2  Column3
0       38       97       38
1       36       86       55
2       11       29       76
3       29       33       88
4       45       90      100


# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [61]:
import pandas as pd
import numpy as np

def replace_negative_with_zero(df, column_name):
    if column_name not in df.columns:
        print(f"Column '{column_name}' not found in DataFrame.")
        return

    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])

data = {'A': [-1, 2, -3, 4, -5],
        'B': [10, -20, 30, -40, 50]}
df = pd.DataFrame(data)

print("Before replacing negative values with zeros:")
print(df)

replace_negative_with_zero(df, 'A')

print("\nAfter replacing negative values in column 'A' with zeros:")
print(df)

Before replacing negative values with zeros:
   A   B
0 -1  10
1  2 -20
2 -3  30
3  4 -40
4 -5  50

After replacing negative values in column 'A' with zeros:
   A   B
0  0  10
1  2 -20
2  0  30
3  4 -40
4  0  50


# 26. Access the 3rd element from the given NumPy array.
       arr = np.array([10, 20, 30, 40, 50])

In [31]:
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

30


# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
        arr_2d = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

In [32]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]
print(element)

6


# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
        arr = np.array([3, 8, 2, 10, 5, 7])

In [33]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

result = arr[arr > 5]

print(result)

[ 8 10  7]


# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
        arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr = arr[2:6]
print(sliced_arr)

[3 4 5 6]


# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
            arr_2d = np.array([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]])

In [36]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [37]:
import numpy as np

def extract_elements(arr, indices):

    flat_arr = arr.flatten()

    extracted_elements = flat_arr[indices]

    return extracted_elements

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

indices = np.array([1, 4, 7])

result = extract_elements(arr, indices)
print(result)

[2 5 8]


# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [1]:
import numpy as np

def filter_greater_than_threshold(arr, threshold):

    return arr[arr > threshold]

input_array = np.array([1, 5, 8, 3, 10, 7])
threshold_value = 5
filtered_array = filter_greater_than_threshold(input_array, threshold_value)
print(filtered_array)

[ 8 10  7]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [2]:
import numpy as np

def extract_elements_3d(array_3d, x_indices, y_indices, z_indices):

    x_indices = np.asarray(x_indices)
    y_indices = np.asarray(y_indices)
    z_indices = np.asarray(z_indices)
    
    if not (x_indices.shape == y_indices.shape == z_indices.shape):
        raise ValueError("All index arrays must have the same length.")
    
    extracted_elements = array_3d[x_indices, y_indices, z_indices]
    
    return extracted_elements

array_3d = np.arange(27).reshape((3, 3, 3))
x_indices = np.array([0, 1, 2])
y_indices = np.array([0, 1, 2])
z_indices = np.array([0, 1, 2])

extracted_elements = extract_elements_3d(array_3d, x_indices, y_indices, z_indices)
print(extracted_elements)

[ 0 13 26]


# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [3]:
import numpy as np

def filter_array_with_conditions(array, condition1, condition2):

    mask1 = condition1(array)
    mask2 = condition2(array)
    
    combined_mask = mask1 & mask2
    
    filtered_array = array[combined_mask]
    
    return filtered_array

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition1 = lambda x: x > 4
condition2 = lambda x: x % 2 == 0

filtered_elements = filter_array_with_conditions(array, condition1, condition2)
print(filtered_elements)

[ 6  8 10]


# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [4]:
import numpy as np

def extract_elements(arr, row_indices, col_indices):

    if len(row_indices) != len(col_indices):
        raise ValueError("Row and column indices arrays must have the same length")
    
    return arr[row_indices, col_indices]

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])

extracted_elements = extract_elements(arr, row_indices, col_indices)
print(extracted_elements)

[3 5 7]


# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = arr + 5

print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [6]:
import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr1_transposed = arr1.T 

result = arr1_transposed * arr2

print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [7]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])

arr2 = np.array([
    [5, 6, 7],
    [8, 9, 10],
    [11, 12, 13],
    [14, 15, 16]
])

arr2_transposed = arr2.T

result_transposed = arr2_transposed + arr1

result = result_transposed.T

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("result:\n", result)

arr1:
 [[1 2 3 4]]
arr2:
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]
result:
 [[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting

In [10]:
import numpy as np

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2

result

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [11]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4]])

arr2_extended = np.hstack((arr2, arr2[:, -1].reshape(-1, 1)))

result = arr1 * arr2_extended

print("arr1:\n", arr1)
print("arr2 extended:\n", arr2_extended)
print("Result of multiplication:\n", result)

arr1:
 [[1 2 3]
 [4 5 6]]
arr2 extended:
 [[1 2 2]
 [3 4 4]]
Result of multiplication:
 [[ 1  4  6]
 [12 20 24]]


# 41. Calculate column wise mean for the given array:
            arr = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_means = np.mean(arr, axis=0)

print("Column-wise mean:", column_means)

Column-wise mean: [2.5 3.5 4.5]


# 42. Find maximum value in each row of the given array:
        arr = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

max_values = np.amax(arr, axis=1)

print("Maximum values in each row:", max_values)

Maximum values in each row: [3 6]


# 43. For the given array, find indices of maximum value in each column.
          arr = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

max_indices = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:", max_indices)

Indices of maximum value in each column: [1 1 1]


# 44. For the given array, apply custom function to calculate moving sum along rows.
            arr = np.array([[1, 2, 3], [4, 5, 6]])

In [17]:
import numpy as np

def moving_sum(arr):
    return np.cumsum(arr, axis=1)

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = moving_sum(arr)
print(result)

[[ 1  3  6]
 [ 4  9 15]]


# 45. In the given array, check if all elements in each column are even.
            arr = np.array([[2, 4, 6], [3, 5, 7]])

In [18]:
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])

are_columns_even = np.all(arr % 2 == 0, axis=0)

print(are_columns_even)

[False False False]


# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
              original_array = np.array([1, 2, 3, 4, 5, 6])

In [19]:
import numpy as np

def reshape_array(arr, m, n):
    reshaped_matrix = arr.reshape(m, n)
    return reshaped_matrix

original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
reshaped_matrix = reshape_array(original_array, m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


# 47. Create a function that takes a matrix as input and returns the flattened array.
                 input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [20]:
import numpy as np

def flatten_matrix(input_matrix):
    flattened_array = input_matrix.flatten()
    return flattened_array

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


# 48. Write a function that concatenates two given arrays along a specified axis.
              array1 = np.array([[1, 2], [3, 4]])
              array2 = np.array([[5, 6], [7, 8]])

In [21]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(concatenated_array)

concatenated_array = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:")
print(concatenated_array)

Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
                original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
import numpy as np

def split_array(original_array, axis, num_splits):
    return np.split(original_array, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = split_array(original_array, axis=0, num_splits=3)
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
            original_array = np.array([1, 2, 3, 4, 5])
            indices_to_insert = [2, 4]
            values_to_insert = [10, 11]
            indices_to_delete = [1, 3]

In [23]:
import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)
    
    original_array = np.delete(original_array, indices_to_delete)
    
    return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)

[ 1 10 11  4  5]


# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [7]:
import numpy as np

arr1 = np.random.randint(1, 100, size=(10, 10))
print("arr1:")
print(arr1)

arr2 = np.arange(1, 11)
print("\narr2:")
print(arr2)

result = np.add(arr1, arr2)
print("\nResult of element-wise addition:")
print(result)

arr1:
[[82 13 49 87  1 56 46 16 41 49]
 [ 3 86 73  1 82 90 66 34 59 66]
 [87 31 66 73 15 62 47 24  7 96]
 [86 11 49 28 35 63 15 33 96  2]
 [58  1 66 89 35 54 42 29 48 22]
 [98 65 50 15 14 94 55 70 52 67]
 [69 27 56 15 45 55  5 39 86 50]
 [15 92 32 44 20 96 71 83 34 85]
 [17 28 46 41 43 37 10  5 56 79]
 [20 65 98 33 73 42 55 24 62 49]]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise addition:
[[ 83  15  52  91   6  62  53  24  50  59]
 [  4  88  76   5  87  96  73  42  68  76]
 [ 88  33  69  77  20  68  54  32  16 106]
 [ 87  13  52  32  40  69  22  41 105  12]
 [ 59   3  69  93  40  60  49  37  57  32]
 [ 99  67  53  19  19 100  62  78  61  77]
 [ 70  29  59  19  50  61  12  47  95  60]
 [ 16  94  35  48  25 102  78  91  43  95]
 [ 18  30  49  45  48  43  17  13  65  89]
 [ 21  67 101  37  78  48  62  32  71  59]]


# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [8]:
import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of subtraction:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [12]:
import numpy as np

arr1 = np.random.randint(1, 10, size=(5, 5))
print("arr1:")
print(arr1)

arr2 = np.arange(1, 6)
print("\narr2:")
print(arr2)

result = arr1 * arr2
print("\nResult of element-wise multiplication:")
print(result)

arr1:
[[1 5 7 4 2]
 [8 7 8 8 9]
 [7 2 8 1 8]
 [5 5 8 9 3]
 [9 9 7 7 9]]

arr2:
[1 2 3 4 5]

Result of element-wise multiplication:
[[ 1 10 21 16 10]
 [ 8 14 24 32 45]
 [ 7  4 24  4 40]
 [ 5 10 24 36 15]
 [ 9 18 21 28 45]]


# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [13]:
import numpy as np

arr1 = np.arange(2, 11, 2)

arr2 = np.arange(1, 6)

result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise division:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result of element-wise division: [2. 2. 2. 2. 2.]


# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [14]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.flip(arr1)

result = np.power(arr1, arr2)

print(result)

[ 1 16 27 16  5]


# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
        arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [15]:
import numpy as np

def count_substring_occurrences(array, substring):

    flat_array = array.flatten()

    counts = np.char.count(flat_array, substring)

    total_count = np.sum(counts)
    
    return total_count

array = np.array(["hello", "world", "hello", "numpy"])
substring = "hello"
print(count_substring_occurrences(array, substring))

2


# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
        arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [18]:
import numpy as np

def extract_uppercase(arr):
    upper_chars = np.array([''.join(filter(str.isupper, word)) for word in arr])
    return upper_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print(uppercase_chars)

['H' 'W' 'OAI' 'GPT']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
       arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [19]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):

    replaced = np.core.defchararray.replace(arr, old_substring, new_substring)
    return replaced

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring(arr, 'apple', 'orange')
print(new_arr)

['orange' 'banana' 'grape' 'pineorange']


# 59. Write a function that concatenates strings in a NumPy array element-wise.
         arr1 = np.array(['Hello', 'World'])
         arr2 = np.array(['Open', 'AI'])

In [20]:
import numpy as np

def concatenate_strings_elementwise(arr1, arr2):
    concatenate_func = np.vectorize(lambda x, y: x + y)
    return concatenate_func(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_strings_elementwise(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


# 60. Write a function that finds the length of the longest string in a NumPy array.
         arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [21]:
import numpy as np

def longest_string_length(arr):

    lengths = [len(str(s)) for s in arr]

    max_length = max(lengths)
    return max_length

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))

9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [22]:
import numpy as np

dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)

median = np.median(dataset)

variance = np.var(dataset)

std_dev = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Dataset: [687 247  87 904 264 990 995 797 278 720 904 602 381 976 322 252 393 663
 384 819 229 370 887 460 619 386 604 844 207 762 328 590 975 517 789 626
 712 497  75 390 291 222 425 522 714 173 742 300 386  11 152 262 526 127
 522 748 145 124 951 356 930 776 106 174 966  74 669 647 135 364 241 542
 902 644  71 383 952  94  81 164  48 953 500 586 502 964 872 990 342 939
 571 869  10 916 540 706  78 969 783 834]
Mean: 521.18
Median: 522.0
Variance: 90762.26759999999
Standard Deviation: 301.2677672768861


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [23]:
import numpy as np

random_numbers = np.random.randint(1, 101, 50)

percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

print("Array of random numbers:", random_numbers)
print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)

Array of random numbers: [ 13   5  91  22  80  79  92  57  33  86  93   2  95  87  17  85   5  62
  35  56  43 100   8   8  16  68  60  85  76  67   8  37  99  30  34  62
  28   6  49  87  50   1  13  50  40  41  52  72  36  87]
25th percentile: 23.5
75th percentile: 79.75


# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [24]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: -0.9999999999999999


# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [25]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [26]:
import numpy as np

array = np.random.randint(10, 1001, 50)

percentiles = np.percentile(array, [10, 25, 50, 75, 90])

print("Array:", array)
print("10th percentile:", percentiles[0])
print("25th percentile (first quartile):", percentiles[1])
print("Median (50th percentile):", percentiles[2])
print("75th percentile (third quartile):", percentiles[3])
print("90th percentile:", percentiles[4])

Array: [748 990 507 562 340 998 910 252 871 907 162 157 875 310  11 747  62 789
 930 122 688 886 821  27 202 172 203 597 220 358 760 423 511 920 748 415
 104 101 245  75 671 899 648 460  67  34 282 665 560 449]
10th percentile: 74.2
25th percentile (first quartile): 202.25
Median (50th percentile): 483.5
75th percentile (third quartile): 757.0
90th percentile: 907.3


# 66. Create a NumPy array of integers and find the index of a specific element.

In [27]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

element_to_find = 6

index = np.where(array == element_to_find)[0]

if len(index) > 0:
    print("Element", element_to_find, "found at index:", index[0])
else:
    print("Element", element_to_find, "not found in the array.")

Element 6 found at index: 5


# 67. Generate a random NumPy array and sort it in ascending order.

In [28]:
import numpy as np

random_array = np.random.rand(10)

sorted_array = np.sort(random_array)

print("Random array:", random_array)
print("Sorted array:", sorted_array)

Random array: [0.60369613 0.10345987 0.64555587 0.48664869 0.86236089 0.38217683
 0.30565673 0.76789419 0.472784   0.02423443]
Sorted array: [0.02423443 0.10345987 0.30565673 0.38217683 0.472784   0.48664869
 0.60369613 0.64555587 0.76789419 0.86236089]


# 68. Filter elements >20  in the given NumPy array.
        arr = np.array([12, 25, 6, 42, 8, 30])

In [29]:
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print(filtered_arr)

[25 42 30]


# 69. Filter elements which are divisible by 3 from a given NumPy array.
        arr = np.array([1, 5, 8, 12, 15])

In [30]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])

divisible_by_3 = arr[arr % 3 == 0]

print(divisible_by_3)

[12 15]


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
         arr = np.array([10, 20, 30, 40, 50])

In [31]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print(filtered_arr)

[20 30 40]


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
          arr = np.array([1, 2, 3])

In [39]:
import numpy as np

arr = np.array([1, 2, 3,])

print('Array:', arr)
 
print('Datatype:', arr.dtype)

Array: [1 2 3]
Datatype: int64


# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
        arr = np.array([1, 2, 3], dtype=np.int32)

In [40]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(True)

print("Byte swapped array:", arr)

Byte swapped array: [16777216 33554432 50331648]


# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
         arr = np.array([1, 2, 3], dtype=np.int32)

In [42]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)

Original array: [1 2 3]
Swapped byte order array: [16777216 33554432 50331648]


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
         arr = np.array([1, 2, 3], dtype=np.int32)

In [47]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

if sys.byteorder == 'little': 
    arr = arr.newbyteorder('big')
else:
    arr = arr.newbyteorder('little') 

print(arr)

[16777216 33554432 50331648]


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
           arr = np.array([1, 2, 3], dtype=np.int32)

In [48]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder != '=':
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")

Byte swapping is not necessary for the current system.


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [49]:
import numpy as np

arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 100

print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)

Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [50]:
import numpy as np

matrix = np.random.randint(0, 10, (3, 3))

print("Original Matrix:")
print(matrix)

view_slice = matrix[:2, :2]

print("\nExtracted Slice:")
print(view_slice)

view_slice[0, 0] = 999

print("\nModified Slice:")
print(view_slice)

print("\nOriginal Matrix After Modification:")
print(matrix)

Original Matrix:
[[6 8 1]
 [7 3 9]
 [3 7 6]]

Extracted Slice:
[[6 8]
 [7 3]]

Modified Slice:
[[999   8]
 [  7   3]]

Original Matrix After Modification:
[[999   8   1]
 [  7   3   9]
 [  3   7   6]]


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [51]:
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[:2, :2]

view_b += 5

print("Original array_a:")
print(array_a)

Original array_a:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [52]:
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
print("Original Array:")
print(orig_array)

reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped View:")
print(reshaped_view)

reshaped_view[1, 0] = 100

print("\nModified Original Array:")
print(orig_array)

Original Array:
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified Original Array:
[[  1   2 100   4]
 [  5   6   7   8]]


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [53]:
import numpy as np

data = np.random.randint(0, 10, size=(3, 4))
print("Original data:")
print(data)

data_copy = data[data > 5].copy()
print("\nCopied data (elements greater than 5):")
print(data_copy)

if data_copy.size > 0:
    data_copy[0] = 10

print("\nOriginal data after modifying data_copy:")
print(data)

Original data:
[[5 2 4 9]
 [3 6 9 3]
 [9 3 3 5]]

Copied data (elements greater than 5):
[9 6 9 9]

Original data after modifying data_copy:
[[5 2 4 9]
 [3 6 9 3]
 [9 3 3 5]]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [54]:
import numpy as np

rows = 3
cols = 3

A = np.random.randint(1, 10, size=(rows, cols))

B = np.random.randint(1, 10, size=(rows, cols))

addition_result = A + B

subtraction_result = A - B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition Result:")
print(addition_result)
print("\nSubtraction Result:")
print(subtraction_result)

Matrix A:
[[7 8 9]
 [6 8 8]
 [7 9 7]]

Matrix B:
[[8 7 8]
 [5 1 6]
 [5 3 9]]

Addition Result:
[[15 15 17]
 [11  9 14]
 [12 12 16]]

Subtraction Result:
[[-1  1  1]
 [ 1  7  2]
 [ 2  6 -2]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [55]:
import numpy as np

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

result = np.dot(C, D)

print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nResult of matrix multiplication (C * D):")
print(result)

Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]

Matrix D (2x4):
[[ 7  8  9 10]
 [11 12 13 14]]

Result of matrix multiplication (C * D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


# 83. Create a matrix `E` and find its transpose.

In [56]:
import numpy as np

E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Matrix E:")
print(E)

E_transpose = np.transpose(E)

print("\nTranspose of matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 84. Generate a square matrix `F` and compute its determinant.

In [59]:
import numpy as np

F = np.random.rand(4, 4)

determinant = np.linalg.det(F)

print("Matrix F:")
print(F)
print("\nDeterminant of F:", determinant)

Matrix F:
[[0.29531488 0.41061933 0.93076972 0.4125042 ]
 [0.93755607 0.3435442  0.73876194 0.65777985]
 [0.88518667 0.63903515 0.44814911 0.33550398]
 [0.68351524 0.03775489 0.03422074 0.89503886]]

Determinant of F: 0.15678820823591527


# 85. Create a square matrix `G` and find its inverse.

In [60]:
import numpy as np

G = np.random.rand(3, 3)

print("Original Matrix G:")
print(G)

G_inverse = np.linalg.inv(G)

print("\nInverse of Matrix G:")
print(G_inverse)

Original Matrix G:
[[0.71534113 0.15668379 0.84813083]
 [0.12681855 0.33957028 0.42548576]
 [0.61043322 0.97268593 0.86706334]]

Inverse of Matrix G:
[[ 0.89696901 -5.1752844   1.66223464]
 [-1.12479423 -0.76992642  1.4780528 ]
 [ 0.63032516  4.50723949 -1.67503842]]
